version: "3"

services:
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
